<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <ProjectReference Include="../Domain/Ehsms.Modules.SafetyRisk.Domain.csproj" />
    <ProjectReference Include="../Application/Ehsms.Modules.SafetyRisk.Application.csproj" />
    <ProjectReference Include="../Contracts/Ehsms.Modules.SafetyRisk.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Ehsms.BuildingBlocks.csproj" />
    <ProjectReference Include="../../Platform/Contracts/Ehsms.Modules.Platform.Contracts.csproj" />
  </ItemGroup>
</Project>