<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Domain/Ehsms.Modules.ComplianceContracts.Domain.csproj" /><ProjectReference Include="../Contracts/Ehsms.Modules.ComplianceContracts.Contracts.csproj" /><ProjectReference Include="../../../BuildingBlocks/Ehsms.BuildingBlocks.csproj" /></ItemGroup></Project>