<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Domain/Ehsms.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="../Application/Ehsms.Modules.Identity.Application.csproj" />
    <ProjectReference Include="../Contracts/Ehsms.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="../../../BuildingBlocks/Ehsms.BuildingBlocks.csproj" />
  </ItemGroup>
</Project>
