<Project Sdk="Microsoft.NET.Sdk"><ItemGroup><ProjectReference Include="../Domain/Ehsms.Modules.HealthSafety.Domain.csproj" /><ProjectReference Include="../Contracts/Ehsms.Modules.HealthSafety.Contracts.csproj" /><ProjectReference Include="../../../BuildingBlocks/Ehsms.BuildingBlocks.csproj" /></ItemGroup></Project>